# 版權所有 2025 Google LLC
#
# 根據 Apache 授權條款第 2.0 版（「授權」）授權。
# 除非遵守授權，否則不得使用此檔案。
# 您可以在以下網址取得授權副本：
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# 除非適用法律要求或書面同意，否則本軟體以「現狀」方式分發，
# 不附帶任何明示或暗示的擔保。
# 詳情請參閱授權條款以瞭解相關權利與限制。

steps:
  # 建置並推送映像檔
  # 此步驟會使用 Docker 建立映像檔並推送到 Artifact Registry。
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME',
        '--build-arg',
        'COMMIT_SHA=$COMMIT_SHA',
        '.',
      ]
  # 推送映像檔到 Artifact Registry。
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME',
      ]

  # 部署到 Staging 環境
  # 使用 gcloud 將映像檔部署到 Cloud Run 的 Staging 專案。
  - name: 'gcr.io/cloud-builders/gcloud'
    id: deploy-staging
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pack-policy-as-code'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME'
      - '--region'
      - '${_REGION}'
      - '--project'
      - '${_STAGING_PROJECT_ID}'

  # 取得 Staging 服務的 URL
  # 透過 gcloud 查詢 Cloud Run 服務網址並存到 staging_url.txt。
  - name: 'gcr.io/cloud-builders/gcloud'
    id: fetch-staging-url
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo $(gcloud run services describe pack-policy-as-code \
        --region ${_REGION} --project ${_STAGING_PROJECT_ID} --format="value(status.url)") > staging_url.txt

  # 取得 ID Token
  # 產生身分驗證用的 ID Token 並存到 id_token.txt。
  - name: gcr.io/cloud-builders/gcloud
    id: fetch-id-token
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo $(gcloud auth print-identity-token -q) > id_token.txt

  # 負載測試
  # 使用 Locust 進行 API 負載測試，並產生測試報告。
  - name: 'python:3.12-slim'
    id: load_test
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        export _ID_TOKEN=$(cat id_token.txt)
        export _STAGING_URL=$(cat staging_url.txt)
        pip install locust==2.31.1 --user
        locust -f tests/load_test/load_test.py \
        --headless \
        -H $$_STAGING_URL \
        -t 30s -u 10 -r 0.5 \
        --csv=tests/load_test/.results/results \
        --html=tests/load_test/.results/report.html
    env:
      - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # 匯出負載測試結果到 GCS
  # 將測試結果資料夾複製到 Google Cloud Storage，並顯示存放路徑。
  - name: gcr.io/cloud-builders/gcloud
    id: export-results-to-gcs
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        export _TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        gsutil -m cp -r tests/load_test/.results gs://${_LOGS_BUCKET_NAME_STAGING}/load-test-results/results-$${_TIMESTAMP}
        echo "_________________________________________________________________________"
        echo "負載測試結果已複製到 gs://${_LOGS_BUCKET_NAME_STAGING}/load-test-results/results-$${_TIMESTAMP}"
        echo "HTTP 連結: https://console.cloud.google.com/storage/browser/${_LOGS_BUCKET_NAME_STAGING}/load-test-results/results-$${_TIMESTAMP}"
        echo "_________________________________________________________________________"

  # 觸發正式環境部署
  # 透過 Cloud Build trigger 觸發正式環境的部署流程。
  - name: gcr.io/cloud-builders/gcloud
    id: trigger-prod-deployment
    entrypoint: gcloud
    args:
      - 'beta'
      - 'builds'
      - 'triggers'
      - 'run'
      - 'deploy-pack-policy-as-code'
      - '--region'
      - '$LOCATION'
      - '--project'
      - '$PROJECT_ID'
      - '--sha'
      - $COMMIT_SHA

  # 顯示正式部署觸發連結
  # 顯示 Cloud Build Console 的連結，方便檢視或核准正式部署進度。
  - name: gcr.io/cloud-builders/gcloud
    id: echo-view-build-trigger-link
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        echo "_________________________________________________________________________"
        echo "已觸發正式部署。可至 Cloud Build Console 檢視進度或核准："
        echo "https://console.cloud.google.com/cloud-build/builds;region=$LOCATION"
        echo "_________________________________________________________________________"

substitutions:
  _STAGING_PROJECT_ID: YOUR_STAGING_PROJECT_ID # Staging 專案 ID，請替換為實際值
  _REGION: us-central1 # 部署區域，預設為 us-central1

logsBucket: gs://${PROJECT_ID}-pack-policy-as-code-logs/build-logs # 建置日誌儲存桶
options:
  substitutionOption: ALLOW_LOOSE # 允許替換變數未完全定義
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET # 使用區域性且使用者自有的儲存桶
