import type {
  Content,
  FunctionCall,
  GenerationConfig,
  GenerativeContentBlob,
  Part,
  Tool,
} from "@google/generative-ai";

/**
 * this module contains type-definitions and Type-Guards
 * 此模組包含類型定義和類型守衛 (Type-Guards)
 */

// Type-definitions
// 類型定義

/* outgoing types */
/* 發送出的訊息類型 (Outgoing) */

/**
 * the config to initiate the session
 * 用於初始化工作階段的配置
 */
export type LiveConfig = {
  model: string; // 使用的模型名稱
  systemInstruction?: { parts: Part[] }; // 系統指令，定義模型的行為
  generationConfig?: Partial<LiveGenerationConfig>; // 生成內容的配置
  tools?: Array<Tool | { googleSearch: {} } | { codeExecution: {} }>; // 可用的工具列表，如 Google 搜尋或程式碼執行
};

/**
 * Configuration for live generation
 * 即時生成的配置
 */
export type LiveGenerationConfig = GenerationConfig & {
  responseModalities: "text" | "audio" | "image"; // 回應的模態：文字、音訊或影像
  speechConfig?: {
    voiceConfig?: {
      prebuiltVoiceConfig?: {
        voiceName: "Puck" | "Charon" | "Kore" | "Fenrir" | "Aoede" | string; // 預設語音名稱
      };
    };
  };
};

/**
 * Union type for all outgoing messages
 * 所有發送訊息的聯合類型
 */
export type LiveOutgoingMessage =
  | SetupMessage
  | ClientContentMessage
  | RealtimeInputMessage
  | ToolResponseMessage;

/**
 * Message to set up the connection
 * 用於建立連接的訊息
 */
export type SetupMessage = {
  setup: LiveConfig;
};

/**
 * Message containing client content
 * 包含客戶端內容的訊息
 */
export type ClientContentMessage = {
  clientContent: {
    turns: Content[]; // 對話輪次內容
    turnComplete: boolean; // 該輪次是否結束
  };
};

/**
 * Real-time input message (e.g., audio/video chunks)
 * 即時輸入訊息 (例如：音訊/視訊區塊)
 */
export type RealtimeInputMessage = {
  realtimeInput: {
    mediaChunks: GenerativeContentBlob[]; // 媒體數據區塊
  };
};

/**
 * Response message from a tool execution
 * 工具執行後的回應訊息
 */
export type ToolResponseMessage = {
  toolResponse: {
    functionResponses: LiveFunctionResponse[]; // 函數執行結果列表
  };
};

export type ToolResponse = ToolResponseMessage["toolResponse"];

/**
 * Response from a specific function call
 * 特定函數調用的回應
 */
export type LiveFunctionResponse = {
  response: object; // 函數回傳的結果物件
  id: string; // 對應的函數調用 ID
};

/** Incoming types */
/** 接收到的訊息類型 (Incoming) */

/**
 * Union type for all incoming messages
 * 所有接收訊息的聯合類型
 */
export type LiveIncomingMessage =
  | ToolCallMessage
  | ToolCallCancellationMessage
  | SetupCompleteMessage
  | ServerContentMessage
  | AdkEvent;

/**
 * Message indicating setup is complete
 * 指示設置已完成的訊息
 */
export type SetupCompleteMessage = { setupComplete: {} };

/**
 * Message containing content from the server
 * 包含來自伺服器內容的訊息
 */
export type ServerContentMessage = {
  serverContent: ServerContent;
};

/**
 * Union type for server content
 * 伺服器內容的聯合類型
 */
export type ServerContent = ModelTurn | TurnComplete | Interrupted;

/**
 * Content generated by the model
 * 模型生成的內容
 */
export type ModelTurn = {
  modelTurn: {
    parts: Part[]; // 內容部分
  };
};

/**
 * Indicator that a turn is complete
 * 指示對話輪次已完成
 */
export type TurnComplete = { turnComplete: boolean };

/**
 * Indicator that the generation was interrupted
 * 指示生成過程被中斷
 */
export type Interrupted = { interrupted: true };

/**
 * Message to cancel a tool call
 * 取消工具調用的訊息
 */
export type ToolCallCancellationMessage = {
  toolCallCancellation: {
    ids: string[]; // 要取消的工具調用 ID 列表
  };
};

export type ToolCallCancellation =
  ToolCallCancellationMessage["toolCallCancellation"];

/**
 * Message requesting a tool call
 * 請求工具調用的訊息
 */
export type ToolCallMessage = {
  toolCall: ToolCall;
};

/**
 * Definition of a live function call
 * 即時函數調用的定義
 */
export type LiveFunctionCall = FunctionCall & {
  id: string; // 函數調用的唯一標識符
};

/**
 * A `toolCall` message
 * `toolCall` 訊息，包含一個或多個函數調用
 */
export type ToolCall = {
  functionCalls: LiveFunctionCall[];
};

/** log types */
/** 日誌類型 */
export type StreamingLog = {
  date: Date; // 日誌時間
  type: string; // 日誌類型
  count?: number; // 計數 (可選)
  message: string | LiveOutgoingMessage | LiveIncomingMessage; // 日誌訊息內容
};

// Type-Guards
// 類型守衛 (用於在執行時檢查類型)

const prop = (a: any, prop: string) =>
  typeof a === "object" && typeof a[prop] === "object";

// outgoing messages
// 發送訊息的類型守衛

export const isSetupMessage = (a: unknown): a is SetupMessage =>
  prop(a, "setup");

export const isClientContentMessage = (a: unknown): a is ClientContentMessage =>
  prop(a, "clientContent");

export const isRealtimeInputMessage = (a: unknown): a is RealtimeInputMessage =>
  prop(a, "realtimeInput");

export const isToolResponseMessage = (a: unknown): a is ToolResponseMessage =>
  prop(a, "toolResponse");

// incoming messages
// 接收訊息的類型守衛

export const isSetupCompleteMessage = (a: unknown): a is SetupCompleteMessage =>
  prop(a, "setupComplete");

export const isServerContenteMessage = (a: any): a is ServerContentMessage =>
  prop(a, "serverContent");

export const isToolCallMessage = (a: any): a is ToolCallMessage =>
  prop(a, "toolCall");

export const isToolCallCancellationMessage = (
  a: unknown,
): a is ToolCallCancellationMessage =>
  prop(a, "toolCallCancellation") &&
  isToolCallCancellation((a as any).toolCallCancellation);

export const isModelTurn = (a: any): a is ModelTurn =>
  typeof (a as ModelTurn).modelTurn === "object";

export const isTurnComplete = (a: any): a is TurnComplete =>
  typeof (a as TurnComplete).turnComplete === "boolean";

export const isInterrupted = (a: any): a is Interrupted =>
  (a as Interrupted).interrupted;

/**
 * Check if the value is a ToolCall
 * 檢查值是否為工具調用
 */
export function isToolCall(value: unknown): value is ToolCall {
  if (!value || typeof value !== "object") return false;

  const candidate = value as Record<string, unknown>;

  return (
    Array.isArray(candidate.functionCalls) &&
    candidate.functionCalls.every((call) => isLiveFunctionCall(call))
  );
}

/**
 * Check if the value is a ToolResponse
 * 檢查值是否為工具回應
 */
export function isToolResponse(value: unknown): value is ToolResponse {
  if (!value || typeof value !== "object") return false;

  const candidate = value as Record<string, unknown>;

  return (
    Array.isArray(candidate.functionResponses) &&
    candidate.functionResponses.every((resp) => isLiveFunctionResponse(resp))
  );
}

/**
 * Check if the value is a LiveFunctionCall
 * 檢查值是否為即時函數調用
 */
export function isLiveFunctionCall(value: unknown): value is LiveFunctionCall {
  if (!value || typeof value !== "object") return false;

  const candidate = value as Record<string, unknown>;

  return (
    typeof candidate.name === "string" &&
    typeof candidate.id === "string" &&
    typeof candidate.args === "object" &&
    candidate.args !== null
  );
}

/**
 * Check if the value is a LiveFunctionResponse
 * 檢查值是否為即時函數回應
 */
export function isLiveFunctionResponse(
  value: unknown,
): value is LiveFunctionResponse {
  if (!value || typeof value !== "object") return false;

  const candidate = value as Record<string, unknown>;

  return (
    typeof candidate.response === "object" && typeof candidate.id === "string"
  );
}

export const isToolCallCancellation = (
  a: unknown,
): a is ToolCallCancellationMessage["toolCallCancellation"] =>
  typeof a === "object" && Array.isArray((a as any).ids);

// ADK Event types
// ADK 事件類型

export interface AdkEvent {
  invocation_id: string; // 調用 ID
  author: string; // 作者
  actions: {
    state_delta: any; // 狀態變更
    artifact_delta: any; // 成品變更
    requested_auth_configs: any; // 請求的認證配置
    requested_tool_confirmations: any; // 請求的工具確認
  };
  id: string; // 事件 ID
  timestamp: number; // 時間戳
  // Optional ADK fields
  // 可選的 ADK 欄位
  input_transcription?: { text: string }; // 輸入轉錄文本
  output_transcription?: { text: string }; // 輸出轉錄文本
  content?: any; // 內容
  interrupted?: boolean; // 是否中斷
  turn_complete?: boolean; // 輪次是否完成
  partial?: boolean; // 是否為部分內容
  usage_metadata?: {
    prompt_token_count: number; // 提示詞 Token 數量
    total_token_count: number; // 總 Token 數量
    prompt_tokens_details?: any[]; // 提示詞 Token 詳細資訊
  };
}

// ADK Event type guards
// ADK 事件類型守衛

export const isAdkEvent = (a: unknown): a is AdkEvent =>
  typeof a === "object" &&
  a !== null &&
  typeof (a as any).invocation_id === "string" &&
  typeof (a as any).author === "string" &&
  typeof (a as any).actions === "object";

export const isInputTranscription = (a: unknown): a is AdkEvent =>
  isAdkEvent(a) && (a as AdkEvent).input_transcription !== undefined;

export const isOutputTranscription = (a: unknown): a is AdkEvent =>
  isAdkEvent(a) && (a as AdkEvent).output_transcription !== undefined;
